### ISSUE TITLE
Missing tags for releases v0.1.5 and v0.1.6

### ISSUE THREAD

**Issue by donkirkby** [pybee/colosseum#17]
Please tag commit 6f9e93fef7e5cc9f5c923a37b817392eb1bf5d57 for v0.1.6 and 5b33da6d0542dc98d954e17174e2e7282148be8f for v0.1.5, so people can more easily find the version differences.

Thanks.

**Comment by freakboy3742** [comment]
Looks like I had tagged them locally, but not pushed the tags to the repository. Thanks for the report; I've pushed them now.

**Comment by donkirkby** [comment]
Are you sure you pushed them? I just cloned the repo, and I don't see them.

```
$ git clone git@github.com:pybee/colosseum.git
Cloning into 'colosseum'...
remote: Counting objects: 43825, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 43825 (delta 0), reused 1 (delta 0), pack-reused 43820
Receiving objects: 100% (43825/43825), 26.51 MiB | 875.00 KiB/s, done.
Resolving deltas: 100% (35477/35477), done.
Checking connectivity... done.
$ cd colosseum/
$ git tag
v0.1.0
v0.1.1
v0.1.2
v0.1.3
v0.1.4
$
```

Pushing to the wrong remote, perhaps? Pushing without the `--tags` option?

**Comment by freakboy3742** [comment]
Hrm... I *was* sure... Now not so much :-) 

Lets try that again...

**Comment by freakboy3742** [comment]
Ah - I pushed the tags to my fork, but not to the pybee repository. Fixed now.

**Comment by donkirkby** [comment]
Looks good now. Thanks for that.
